[workspace]
authors = ["Mose Schmiedel <mose@schmiednet.de>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge", "pytorch"]
name = "satellit"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.1.0,<8"
tqdm = ">=4.67.1,<5"
requests = ">=2.32.5,<3"
pycocotools = ">=2.0.10,<3"
matplotlib = ">=3.10.8,<4"
onnxruntime = ">=1.22.0,<2"
onnx = ">=1.19.1,<2"
opencv = ">=4.12.0,<5"
numpy = ">=2.3.5,<3"
pip = ">=25.3,<26"
pytorch = ">=2.9.1,<3"
torchvision = ">=0.24.1,<0.25"


[pypi-dependencies]
python-base = { git = "ssh://git@github.com/walderkennung/python-base.git" }

[environments]
cuda = ["cuda"]

[feature.cuda]
dependencies = {cuda = ">=12.0"}
platforms = ["linux-64"]
activation = {scripts = ["cuda_activation.sh"]}
system-requirements = {cuda = "12"}
# Channels concatenate using a priority instead of overwrite, so the default channels are still used.
# Using the priority the concatenation is controlled, default is 0, the default channels are used last.
# Highest priority comes first.
channels = ["nvidia", {channel = "pytorch", priority = -1}] # Results in:  ["nvidia", "conda-forge", "pytorch"] when the default is `conda-forge`
tasks = { warmup = "python warmup.py" }
