import csv
import os
import re
from pathlib import Path


BBOX_DELIMITER = ","
TILE_FILENAME_PATTERN = re.compile(r"^tile_x(-?\d+)_y(-?\d+)\.png$")


def parse_bbox_prompt(raw_bbox: str) -> tuple[float, float, float, float]:
    """Parse one bbox prompt in ``x1,y1,x2,y2`` format.

    Args:
        raw_bbox: Raw prompt string from CLI input.

    Returns:
        Parsed box tuple ``(x1, y1, x2, y2)``.

    Raises:
        ValueError: If formatting or coordinate ordering is invalid.
    """
    parts = [part.strip() for part in raw_bbox.split(BBOX_DELIMITER)]
    if len(parts) != 4:
        raise ValueError(
            f"Invalid bbox '{raw_bbox}'. Expected format: x1,y1,x2,y2."
        )

    try:
        x1, y1, x2, y2 = (float(value) for value in parts)
    except ValueError as err:
        raise ValueError(
            f"Invalid bbox '{raw_bbox}'. Coordinates must be numeric."
        ) from err

    if x2 <= x1 or y2 <= y1:
        raise ValueError(
            f"Invalid bbox '{raw_bbox}'. Expected x2>x1 and y2>y1."
        )

    return x1, y1, x2, y2


def parse_bbox_prompts(raw_bboxes: list[str] | None) -> list[tuple[float, float, float, float]]:
    """Parse repeatable bbox prompt options.

    Args:
        raw_bboxes: Raw ``--bbox`` values from CLI options.

    Returns:
        Parsed bounding boxes.
    """
    if not raw_bboxes:
        return []

    return [parse_bbox_prompt(raw_bbox) for raw_bbox in raw_bboxes]


def parse_tile_origin(tile_path: str) -> tuple[int, int]:
    """Extract tile origin ``(x, y)`` from a tile filename.

    Args:
        tile_path: Path to a tile image.

    Returns:
        Tile origin in image coordinates.

    Raises:
        ValueError: If the filename does not match the expected tile pattern.
    """
    filename = os.path.basename(tile_path)
    match = TILE_FILENAME_PATTERN.match(filename)
    if match is None:
        raise ValueError(
            f"Could not parse tile origin from '{tile_path}'. "
            "Expected filename like tile_x0_y0.png."
        )

    return int(match.group(1)), int(match.group(2))


def tile_id_from_origin(tile_origin: tuple[int, int]) -> str:
    """Build weak-label tile id from a tile origin tuple.

    Args:
        tile_origin: Tile origin ``(x, y)``.

    Returns:
        Tile identifier in ``tile_x{X}_y{Y}`` form.
    """
    return f"tile_x{tile_origin[0]}_y{tile_origin[1]}"


def load_weak_label_bboxes(
    weak_labels_csv: Path,
) -> dict[str, list[tuple[float, float, float, float]]]:
    """Load tile-local bbox prompts from labels generated by ``label weak``.

    Args:
        weak_labels_csv: Path to ``labels_tiles.csv``.

    Returns:
        Mapping from tile id to local bounding boxes.

    Raises:
        ValueError: If required fields are missing or rows are malformed.
    """
    required_fields = ("tile_id", "bbox_x1", "bbox_y1", "bbox_x2", "bbox_y2")
    bboxes_by_tile: dict[str, list[tuple[float, float, float, float]]] = {}

    with weak_labels_csv.open("r", encoding="utf-8", newline="") as file:
        reader = csv.DictReader(file)
        if reader.fieldnames is None:
            raise ValueError(f"Weak-label CSV has no header: {weak_labels_csv}")
        missing_fields = [field for field in required_fields if field not in reader.fieldnames]
        if missing_fields:
            raise ValueError(
                "Weak-label CSV is missing required bbox columns: "
                + ", ".join(missing_fields)
            )

        for row_index, row in enumerate(reader, start=2):
            tile_id = (row.get("tile_id") or "").strip()
            if not tile_id:
                raise ValueError(
                    f"Weak-label CSV row {row_index} has no tile_id: {weak_labels_csv}"
                )

            try:
                bbox = (
                    float(row["bbox_x1"]),
                    float(row["bbox_y1"]),
                    float(row["bbox_x2"]),
                    float(row["bbox_y2"]),
                )
            except (TypeError, ValueError) as err:
                raise ValueError(
                    f"Weak-label CSV row {row_index} contains non-numeric bbox values."
                ) from err

            x1, y1, x2, y2 = bbox
            if x2 <= x1 or y2 <= y1:
                raise ValueError(
                    f"Weak-label CSV row {row_index} has invalid bbox order."
                )

            bboxes_by_tile.setdefault(tile_id, []).append(bbox)

    return bboxes_by_tile


def project_bboxes_to_tile(
    image_bboxes: list[tuple[float, float, float, float]],
    tile_origin: tuple[int, int],
    tile_size: tuple[int, int],
) -> list[tuple[float, float, float, float]]:
    """Project image-space boxes into one tile as clipped tile-space boxes.

    Args:
        image_bboxes: Boxes in full-image coordinates.
        tile_origin: Tile origin ``(x, y)`` in full-image coordinates.
        tile_size: Tile size ``(width, height)`` in pixels.

    Returns:
        Tile-local boxes that intersect with the tile.
    """
    tile_x, tile_y = tile_origin
    tile_width, tile_height = tile_size
    tile_x_end = tile_x + tile_width
    tile_y_end = tile_y + tile_height

    tile_bboxes: list[tuple[float, float, float, float]] = []
    for x1, y1, x2, y2 in image_bboxes:
        clipped_x1 = max(x1, tile_x)
        clipped_y1 = max(y1, tile_y)
        clipped_x2 = min(x2, tile_x_end)
        clipped_y2 = min(y2, tile_y_end)

        if clipped_x2 <= clipped_x1 or clipped_y2 <= clipped_y1:
            continue

        tile_bboxes.append(
            (
                clipped_x1 - tile_x,
                clipped_y1 - tile_y,
                clipped_x2 - tile_x,
                clipped_y2 - tile_y,
            )
        )

    return tile_bboxes
